namespace Pegasus
{
	public static class PegasusConstants
	{
		public enum FlythroughType
		{
			SingleShot,
			Looped
		}

		public enum FlythroughEndAction
		{
			StopFlythrough,
			QuitApplication,
			PlayNextPegasus
		}

		public enum FlythroughState
		{
			Stopped,
			Initialising,
			Started,
			Paused
		}

		public enum HeightCheckType
		{
			Collision,
			Terrain,
			None
		}

		public enum PoiHeightCheckType
		{
			ManagerSettings,
			Collision,
			Terrain,
			None
		}

		public enum PoiType
		{
			Manual,
			AutoGenerated
		}

		public enum LookatType
		{
			Path,
			Target
		}

		public enum SpeedType
		{
			ReallySlow,
			Slow,
			Medium,
			Fast,
			ReallyFast,
			Stratospheric,
			Custom
		}

		public enum EasingType
		{
			Linear,
			EaseIn,
			EaseOut,
			EaseInOut
		}

		public enum TargetFrameRate
		{
			NineFps,
			FifteenFps,
			TwentyFourFps,
			TwentyFiveFps,
			ThirtyFps,
			SixtyFps,
			NinetyFps,
			MaxFps,
			LeaveAlone
		}

		public enum PegasusAnimationState
		{
			Idle,
			Walking,
			Running
		}

		public enum PoiPegasusTriggerAction
		{
			PlayPegasus,
			PausePegasus,
			ResumePegasus,
			StopPegasus,
			DoNothing
		}

		public enum PoiHeliosTriggerAction
		{
			FadeIn,
			FadeOut,
			DoNothing
		}

		public enum PoiRotateTowardsTriggerAction
		{
			Rotate,
			DoNothing
		}

		public enum PoiAnimationTriggerAction
		{
			PlayAnimation,
			StopAnimation,
			DoNothing
		}

		public static string MajorVersion = "2";

		public static string MinorVersion = "5.2";

		public const float FlybyOffsetDefaultHeight = 1.8f;

		public const float FlybyOffsetLow = 5f;

		public const float FlybyOffsetHigh = 40f;

		public const float SpeedReallySlow = 0.01f;

		public const float SpeedSlow = 1.4f;

		public const float SpeedMedium = 8f;

		public const float SpeedFast = 25f;

		public const float SpeedReallyFast = 70f;

		public const float SpeedStratospheric = 250f;
	}
}
